### ISSUE TITLE
support for passing dataset keys for Zarr files

### ISSUE THREAD

**Issue by Mohinta2892** [kreshuklab/plant-seg#157]
Hi!

I am wondering if it is possible to allow passing specific dataset keys for zarr files (changes anywhere load_stack/smart_load gets called). Right now, the data to be processed needs to be under '/' (root group). However, often pmaps can be stored like 'volumes/pmaps'. The zarr could also contain other keys ('volumes/raw') and I feel plantseg should be able to handle that and just load the dataset specified for processing.

Best, 
Samia

**Comment by qin-yu** [comment]
Hey @lorenzocerrone I think you fixed this by #212?

**Comment by qin-yu** [comment]
This is supported in v2.0.0aX
