### ISSUE TITLE
PyQT is not installed automatically, can't run napari interface

### ISSUE THREAD

**Issue by Buglakova** [kreshuklab/plant-seg#171]
Hello,

When I install plantseg with the command from documentation, it doesn't automatically install Napari's backend, adding `pyqt` explicitly helped:

`mamba create -n plant-seg -c pytorch -c nvidia -c conda-forge -c lcerrone plantseg pytorch-cuda=11.7 cudatoolkit  pyqt`

**Comment by lorenzocerrone** [comment]
Yes, true. Napari changed their build, and now it needs to be specified. I have just added `pyqt` to the installation instructions. @wolny Should we add `pyqt` to the conda recipe or leave it to the user to decide which backend to use?

**Comment by wolny** [comment]
Let's add `pyqt` to the conda recipe, so that it works out of the box.

**Comment by qin-yu** [comment]
This has been fixed, at different levels. As of today, the installation guide and the recipes and config files are all correct.

PS: the `meta.yaml` and environment config files in this repo doesn't affect the conda forge recipe (but feedstock repo does).
