### ISSUE TITLE
Workaround to run plant-seg in colaboratory (with CUDA12.2 as of Jan. 2024)

### ISSUE THREAD

**Issue by totti0223** [kreshuklab/plant-seg#182]
F.Y.I.

```python
!pip install -q condacolab
import condacolab
condacolab.install()
```

```python
!conda install -q -c conda-forge mamba
# https://github.com/conda-incubator/condacolab/issues/60
with open('/usr/local/conda-meta/pinned', 'w') as f:
    f.write("python 3.10.*\npython_abi 3.10.* *cp310*\ncuda-toolkit 12.2.*")
!mamba install -c pytorch -c nvidia -c conda-forge pytorch pytorch-cuda=12.1 pyqt plant-seg
```

```python
!plantseg --config config.yaml
```
![image](https://github.com/hci-unihd/plant-seg/assets/11881238/5e4a34e6-c13a-4676-8980-aaa139843f02)

**Comment by qin-yu** [comment]
Thanks for the issue @totti0223 

I wonder if you can explain more on the actual issue/problem to provide some background information?

If it turns out to be a common issue, we might consider adding it to our troubleshooting section to assist others who might face the same problem in the future.

**Comment by totti0223** [comment]
i really dont know the precise background of this environmental break in condacolab with cuda 12.2, 
the error I encounted when trying to execute the colaboratory notebook which you have deleted recently outputs error message related to condacolab env. setup "cuda pinned not found" or something like that.

found simiar error message in condacolab repo issue and a workaround for it in this thread, tryed and worked.
https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1858067919

i am not sure whether this is a permanent solution to this problem, as  it might be resolved in future update of condacolab or cuda-toolkit.

so i say its a temp workaround for a while.
