### ISSUE TITLE
Transfer PlantSeg from HCI to Kreshuk Lab

### ISSUE THREAD

**Issue by qin-yu** [kreshuklab/plant-seg#194]
To transfer PlantSeg from [Heidelberg Collaboratory for Image Processing](https://github.com/hci-unihd) to [Kreshuk Lab](https://github.com/kreshuklab):

- [x] @lorenzocerrone may follow this guide to transfer: [Transferring a repository owned by your organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-organization)
- [x] ~~@lorenzocerrone may fork the repo back to HCI in case anyone found us using an old link~~
- [x] @lorenzocerrone may check if your conda channel is still updated by the relocated directory
- [x] @wolny do we need to tell conda-forge at all, about the transfer?
- [x] @qin-yu should check the documentation build workflow and GitHub Pages site
- [x] @lorenzocerrone @wolny @qin-yu may update local copy by `git remote set-url origin NEW_URL`

In the end, the only thing we did was to make @qin-yu an admin and press transfer. GitHub pages was migrated automatically and old repo link points to new repo link.

**Comment by lorenzocerrone** [comment]
If we transfer the repo correctly, the old link should still work. Github will redirect anyone that opens the old link to the new repo. 

from https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository:
```
If the transferred repository contains a GitHub Pages site, then links to the Git repository on the Web and through Git activity are redirected. However, we don't redirect GitHub Pages associated with the repository.

All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:

git remote set-url origin NEW_URL
Warning: If you create a new repository or fork at the previous repository location, the redirects to the transferred repository will be deactivated. They can be reactivated by renaming or deleting the new repository or fork.
```

**Comment by imagirom** [comment]
> If we transfer the repo correctly, the old link should still work. Github will redirect anyone that opens the old link to the new repo.

Indeed, here is an example: https://github.com/hci-unihd/YeastCellSeg

**Comment by qin-yu** [comment]
@lorenzocerrone @imagirom hey you are right. I did see this line but quickly forgot it.

**Comment by wolny** [comment]
@qin-yu since the old link will work, we don't have to change the our conda-forge feedstock repo. In the future release we might update to the new URL in here: https://github.com/conda-forge/plant-seg-feedstock/blob/main/recipe/meta.yaml#L8

**Comment by qin-yu** [comment]
In the end, the only thing we did was to make @qin-yu an admin and press transfer. GitHub pages was migrated automatically and old repo link points to new repo link.
