### ISSUE TITLE
`statics_kwargs` vs `runtime_kwargs`

### ISSUE THREAD

**Issue by qin-yu** [kreshuklab/plant-seg#208]
What is the significance to have both keyword args in functions such as `start_prediction_process()` @lorenzocerrone

**Comment by qin-yu** [comment]
Hey @wolny @lorenzocerrone can these be merged into one dict or do they have different roles?

**Comment by lorenzocerrone** [comment]
There is a difference when exporting the DAG for the headless execution. The `statics_kwargs` are the pipeline parameters, while the `runtime_kwargs` are the inputs to the pipeline (the images). 
I think it's essential to keep them separate for now. We can change them when we decide how to redesign the headless mode.
