### ISSUE TITLE
Allow direct search and download from BioImage Model Zoo

### ISSUE THREAD

**Issue by qin-yu** [kreshuklab/plant-seg#210]
Hey @oeway are you coming to EMBL on 11 March? I'll pass by and consult you the best way of allowing users to use models from Zoo in PlantSeg.

**Comment by oeway** [comment]
Unfortunately I won't be able to join, however Weize @Nanguage will join, so please discuss with him.

Not sure what you mean exactly, but maybe you can create a bioengine app for plantseg, basically a tailored version of https://github.com/bioimage-io/bioengine-web-client

**Comment by Nanguage** [comment]
Hi qin-yu, I will participate in the Hackathon. We can communicate face-to-face then!

**Comment by qin-yu** [comment]
### Current PlantSeg model zoo

PlantSeg has a YAML file with hard-coded records of models including the link to weight files on Zenodo.

### Adding BioImage.IO model zoo: Method 1

Since all models from PlantSeg are uploaded to BioImage.IO and Zenodo, we can simply update the list of models in the PlantSeg model zoo at start-up. 

1. Discover all compatible models
2. Avoid duplicate in the local record (by removing current hard-coded record completely?)
3. Separate the dropdown list by a horizontal line and ideally a section name

### Adding BioImage.IO model zoo: Method 2

To minimise the changes, add a widget to let users add a model from BioImage.IO model zoo just like adding a custom model.

1. Discover all compatible models
2. Show models in that widget for users to add

**Comment by qin-yu** [comment]
### Adding BioImage.IO model zoo: Method 3

Why bother running inference on our own code and filter BioImage.IO model zoo? Just use bioimageio.core and use all models available on the zoo : )

**Comment by qin-yu** [comment]
### My Plan

Maybe I don't have to directly change the core of PlantSeg inference to bioimageio.core.

1. Add compatible BioImage.IO model zoo records in PlantSeg on startup
2. Replace PlantSeg hard-coded records by 1
3. Add bioimageio.core as alternative inference engine
4. Replace PlantSeg inference by 3
