### ISSUE TITLE
Cancel split/merge in proofreading

### ISSUE THREAD

**Issue by Buglakova** [kreshuklab/plant-seg#244]
Hello,

I would like to use the proofreading function and it looks like the split/merge would make it much faster, because it actually works in 3D. However, there's no way to cancel if I accidentally merged wrong stuff like here:

![Screenshot from 2024-05-21 15-26-47](https://github.com/kreshuklab/plant-seg/assets/89460016/ff6e437b-2713-4176-b818-301653b52f5b)

Usually Ctrl+Z works in napari but in this case Ctrl+Z only cancels scribbles and not the split/merge result.

**Comment by lorenzocerrone** [comment]
That would definitely be a nice improvement, but we are not currently tracking changes. I am not sure I will be able to add the undo button, but when I update the proofreading, I will try to include it.
