### ISSUE TITLE
Heuristics for parameters: patch size, halo, and rescale factor

### ISSUE THREAD

**Issue by qin-yu** [kreshuklab/plant-seg#250]
I'm planning the following enhancements to PlantSeg that could significantly improve its usability:

- [x] #251

    PlantSeg used a fixed halo that appeared optimal but was potentially influenced by a combination of incorrect padding implementation and a specific input image distribution for testing. Yet we might still be able to assume that input images remain friendly in the future, and therefore reduce the halo for practical reasons. I plan to enable this in `ModelZoo` because it is for all CNNs.
    
    Related discussion:

    -  https://github.com/kreshuklab/plant-seg/pull/248#issuecomment-2132428353
    
- [x] Provide a maximum patch size based on GPU constraints and the decided halo

    Given the GPU resources and the halo dimensions determined, it would be beneficial to define a maximum patch size. I plan to prioritise size in z since we already figured out a theoretical and reliable but possibly oversized halo. e.g. for images with z < 128, I prefer to avoid padding in z dimension. As this requires information of input images as well, I plan to enable this in prediction modules.

    Related PR:

    -  https://github.com/kreshuklab/plant-seg/pull/307

- [x] Provide a rescale factor based on voxel size 

    I plan to make it a part of rescale widget.

    Related issues:

    - #189
    - #217

**Comment by lorenzocerrone** [comment]
Let me know when you want to tackle the rescale, I have some other issues with that widget.
