### ISSUE TITLE
Proofreading tool doesn't allow adding scribbles

### ISSUE THREAD

**Issue by Buglakova** [kreshuklab/plant-seg#280]
Hello,

While using the proofreading tool, the person helping me with annotation encounters the following problem:

Marking with the brush only works half of the time. I am guessing that it is a problem with the layers (I am always on the "scribbles" layer when I correct something, but sometimes it does not let me mark anything...).

I couldn't quite figure out how proofreading tool works so this is how we are using it: 
Switch to Scribles and mark labels to merge with the same number number with brush and parts to split with different numbers. Press "Split/Merge". Then the segmentation in the Labels layer should get corrected.

We are limited in time (the collaborators only have time to work on this until the end of June) and there's no other tool to use for splitting/merging masks rather than drawing from scratch, so any help would be very appreciated!

**Comment by lorenzocerrone** [comment]
Hi, I'm not sure I understand the issue correctly, and I'm sorry for the lack of documents on the proofreading. 

The only case where plantseg might block you from scribbling on a layer is if the label you mark is "protected". Protected labels are used to avoid accidentally ruining a segmentation by mistake. A label is locked if you double-click on it (and vice versa). Could it be that you locked a label by mistake?
