### ISSUE TITLE
allow the use of '-' and 'µm' as unit for voxel size

### ISSUE THREAD

**Issue by AlexisMaizel** [kreshuklab/plant-seg#339]
plant-seg v2 only accepts 'um' as unit size when loading a TIFF file. 
Problem is that Fiji/ImageJ automatically transforms 'um' to 'µm'. Plantseg should also accept µ (U+00B5) and if possible also '-'
Many thanks in advance.

**Comment by qin-yu** [comment]
I see the problem now. I only allowed mu character but not micro sign

![image](https://github.com/user-attachments/assets/44f2fbd0-a2c9-4eba-b3cd-97bfbe63329c)
