### ISSUE TITLE
Question regarding one repeated volume across splits

### ISSUE THREAD

**Issue by anwai98** [kreshuklab/plant-seg#345]
Hi team,

I would like to report something I recently spotted in the PlantSeg (Root) dataset. It seems like there's a volume (`Movie1_t00045_crop_gt.h5`) which exists in both train and test splits. I double checked and looks like both the volumes are identical.

cc: @constantinpape

**Comment by lorenzocerrone** [comment]
Hi @anwai98,

Thanks for spotting it! 

Luckily the issue affects only the OSF dataset and not the trained models 
(you can see the actual train/val/test split used here https://zenodo.org/records/7765026)

@wolny, I think you are the only one with the right to edit the OSF. Could you check if you can update the project?

**Comment by anwai98** [comment]
Hi @lorenzocerrone,

Thanks for the quick response.

Re: OSF dataset: Yes, that's right. I do see the volumes repeated across split while fetching the data from OSF.

In case it helps, I can recommend removing the aforementioned volume from the train split, as the train split still has a good number of volumes after removing the mentioned volume.

**Comment by lorenzocerrone** [comment]
Yes, I agree the dataset should match the one with used in the plublication.

Thanks again from spotting it!

**Comment by wolny** [comment]
hi @anwai98, thanks for reporting. As already mentioned by Lorenzo, `Movie1_t00045_crop_gt.h5` was not used for training (see: https://zenodo.org/records/7765026/files/config_train.yml). I've removed the file from the train split
