### ISSUE TITLE
Classic GUI is unavailable for PlantSeg 2.0. 

### ISSUE THREAD

**Issue by athulrv** [kreshuklab/plant-seg#350]
Its a pity that Classic PlantSeg GUI is not included in the 2.0 update. It has been very helpful in bulk image processing for biologists. 

Is there any guideline how to install latest plantseg 1.x that includes Classic gui?

Best,
Athul

**Comment by athulrv** [comment]
It would be great if a PlantSeg 1.8 version installation procedure is also available so people could still use the classic gui.

**Comment by AlexisMaizel** [comment]
I totally second @athulrv on this one. In the absence of documentation, it is important that we maintain existing workflows by having the possibility to (re-)install v1.8.x.

**Comment by lorenzocerrone** [comment]
Hi everyone,

I agree with the points raised. PlantSeg 1.8.x should continue to be documented, and we should provide minimal support to ensure it remains functional.

@athulrv, there seems to be a little misunderstanding. The classic PlantSeg GUI, as it was originally implemented, is not compatible with PlantSeg 2. 

While it’s true that we don’t have a direct replacement, a new GUI version for batch processing is in development. This new interface will offer a user experience similar to the old GUI. In addition will also try to be able to accommodate more workflows like nuclei segmentation.

**Comment by athulrv** [comment]
Great if PlantSeg gui replacement can happen in 2.0. Any update on when it would be available? It would be great to have some documentation on how to install 1.8 version with classic gui.

**Comment by athulrv** [comment]
@qin-yu thanks for the update and fix.

@AlexisMaizel, how did you perform batch processing with PlantSeg 2.0? using config file?

**Comment by qin-yu** [comment]
@athulrv yes you use a config file but a new one. Just open an image in PlantSeg Napari and perform what you want to automate, save that example output, and you can now export a workflow. This workflow file is what's used as the new config file. 

We'll document it later.

**Comment by AlexisMaizel** [comment]
You basically only have to modify lines 28 and 29 of the YAML file to specify the paths to the Folder containing the input image and the path to the output folder. 
I paste below the block of code to alter: 
```
inputs:
- export_directory: /home/alexis/Desktop/Anamarija_data/Cells
  input_path: /home/alexis/Desktop/Anamarija_data/Cells/
  name_pattern: '{file_name}_export'
```

**Comment by qin-yu** [comment]
Related issue:

#340
